version: "3"

services:

  epos-latex-webapi:
    image: gcr.io/eposgmbh/latex-service:latest
    restart: always
    build:
      context: ../src/Epos.LaTeX.WebApi
      dockerfile: Dockerfile
    ports:
      - 80:80
