version: "3"

services:

  latex-service:
    image: eposgmbh/latex-service:latest
    restart: always
    build:
      context: ../src/app/Epos.LaTeX.WebApi
      dockerfile: Dockerfile
    ports:
      - 5000:5000
